name: Install Dependencies

on:
  workflow_call:
    inputs:
      fallback-node-version:
        required: false
        type: string
        default: "18"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Read node version from .nvmrc file and fallback to the default node version defined if fails to get the node version from .nvmrc file
      - name: Read Node version from .nvmrc
        id: nvm
        run: |
          if [ -f .nvmrc ]; then
            echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
          else
            echo "NODE_VERSION=${{ inputs.fallback-node-version }}" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
